const enum ErrorCode {
  // Auth Register
  AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",

  // Auth Login
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_VERIFIED = "AUTH_USER_NOT_VERIFIED",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_NOT_FOUND = "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS = "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS = "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND = "AUTH_TOKEN_NOT_FOUND",

  // Auth MFA
  AUTH_MFA_INVALID = "AUTH_MFA_INVALID",
  AUTH_MFA_INVALID_CODE = "AUTH_MFA_INVALID_CODE",
  AUTH_MFA_NOT_ENABLED = "AUTH_MFA_NOT_ENABLED",
  AUTH_MFA_RESEND_CODE_TOO_MANY_REQUESTS = "AUTH_MFA_RESEND_CODE_TOO_MANY_REQUESTS",

  // Access Control Errors
  ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",

  // Validation and Resource Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VERIFICATION_ERROR = "VERIFICATION_ERROR",
  TOO_MANY_ATTEMPTS = "AUTH_TOO_MANY_ATTEMPTS",
}

export { ErrorCode };
